// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Arc2 = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_Arc2, 343);
lv_obj_set_height( ui_Arc2, 323);
lv_obj_set_x( ui_Arc2, 9 );
lv_obj_set_y( ui_Arc2, -4 );
lv_obj_set_align( ui_Arc2, LV_ALIGN_CENTER );
lv_arc_set_value(ui_Arc2, 50);


ui_Colorwheel2 = lv_colorwheel_create(ui_Screen1,true);
lv_obj_set_width( ui_Colorwheel2, 316);
lv_obj_set_height( ui_Colorwheel2, 315);
lv_obj_set_x( ui_Colorwheel2, -2 );
lv_obj_set_y( ui_Colorwheel2, -5 );
lv_obj_set_align( ui_Colorwheel2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Colorwheel2, LV_OBJ_FLAG_HIDDEN );   /// Flags

ui_Button1 = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_Button1, 127);
lv_obj_set_height( ui_Button1, 101);
lv_obj_set_x( ui_Button1, 3 );
lv_obj_set_y( ui_Button1, -46 );
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Switch1 = lv_switch_create(ui_Screen1);
lv_obj_set_width( ui_Switch1, 90);
lv_obj_set_height( ui_Switch1, 43);
lv_obj_set_x( ui_Switch1, 0 );
lv_obj_set_y( ui_Switch1, 54 );
lv_obj_set_align( ui_Switch1, LV_ALIGN_CENTER );


lv_obj_add_event_cb(ui_Arc2, ui_event_Arc2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Colorwheel2, ui_event_Colorwheel2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);

}
